language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
install:
  - python setup.py install
  - pip install coveralls
  - pip install pep8
script:
  - pep8 --max-line-length 100 pyramda
  - python setup.py nosetests
after_success:
  - coveralls
